=== Omkaragrawal/qal/SQL.xsd
<?xml version="1.0" ?>
<xsd:schema elementFormDefault="qualified" targetNamespace="http://www.unifiedbpm.se/XMLschema/DAL/SQL" xmlns="http://www.unifiedbpm.se/XMLschema/DAL/SQL" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:simpleType name="datatypes">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="(integer|string|string(\(.*\))|serial|timestamp)"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="db_types">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="MySQL"/>
      <xsd:enumeration value="PostgreSQL"/>
      <xsd:enumeration value="Oracle"/>
      <xsd:enumeration value="DB2"/>
      <xsd:enumeration value="SQLserver"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="and_or">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="AND"/>
      <xsd:enumeration value="OR"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="index_types">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="UNIQUE"/>
      <xsd:enumeration value="CLUSTERED"/>
      <xsd:enumeration value="NONCLUSTERED"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="constraint_types">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="NOT NULL"/>
      <xsd:enumeration value="UNIQUE"/>
      <xsd:enumeration value="PRIMARY KEY"/>
      <xsd:enumeration value="FOREIGN KEY"/>
      <xsd:enumeration value="CHECK"/>
      <xsd:enumeration value="DEFAULT"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="set_operator">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="UNION"/>
      <xsd:enumeration value="INTERSECT"/>
      <xsd:enumeration value="DIFFERENCE"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="data_source">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="Parameter_Flatfile_Dataset"/>
      <xsd:enumeration value="Parameter_XML_Dataset"/>
      <xsd:enumeration value="Parameter_RDBMS_Dataset"/>
      <xsd:enumeration value="Parameter_Matrix_Dataset"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="csv_dialects">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="excel-tab"/>
      <xsd:enumeration value="excel"/>
      <xsd:enumeration value="unix"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="statement">
    <xsd:choice>
      <xsd:element name="Verb_CREATE_TABLE" type="Verb_CREATE_TABLE"/>
      <xsd:element name="Verb_CREATE_INDEX" type="Verb_CREATE_INDEX"/>
      <xsd:element name="Verb_SELECT" type="Verb_SELECT"/>
      <xsd:element name="Verb_Custom" type="Verb_Custom"/>
      <xsd:element name="Verb_INSERT" type="Verb_INSERT"/>
    </xsd:choice>
  </xsd:complexType>
  <xsd:complexType name="condition_part">
    <xsd:choice>
      <xsd:element name="Parameter_Conditions" type="Parameter_Conditions"/>
      <xsd:element name="Parameter_Condition" type="Parameter_Condition"/>
      <xsd:element name="Parameter_Expression" type="Parameter_Expression"/>
      <xsd:element name="Verb_SELECT" type="Verb_SELECT"/>
      <xsd:element name="Parameter_Expression" type="Parameter_Expression"/>
      <xsd:element name="Parameter_String" type="Parameter_String"/>
      <xsd:element name="Parameter_Numeric" type="Parameter_Numeric"/>
      <xsd:element name="Parameter_Identifier" type="Parameter_Identifier"/>
      <xsd:element name="Parameter_Cast" type="Parameter_Cast"/>
      <xsd:element name="Parameter_Function" type="Parameter_Function"/>
      <xsd:element name="Parameter_IN" type="Parameter_IN"/>
      <xsd:element name="Parameter_Dataset" type="Parameter_Dataset"/>
      <xsd:element name="Parameter_CASE" type="Parameter_CASE"/>
      <xsd:element name="Parameter_Set" type="Parameter_Set"/>
    </xsd:choice>
  </xsd:complexType>
  <xsd:complexType name="tabular_expression_item">
    <xsd:choice>
      <xsd:element name="Verb_SELECT" type="Verb_SELECT"/>
      <xsd:element name="Parameter_Dataset" type="Parameter_Dataset"/>
      <xsd:element name="Parameter_Set" type="Parameter_Set"/>
    </xsd:choice>
  </xsd:complexType>
  <xsd:complexType name="Array_Parameter_String">
    <xsd:choice>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Parameter_String" type="Parameter_String"/>
    </xsd:choice>
  </xsd:complexType>
  <xsd:complexType name="Array_Parameter_Constraint">
    <xsd:choice>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Parameter_Constraint" type="Parameter_Constraint"/>
    </xsd:choice>
  </xsd:complexType>
  <xsd:complexType name="Array_Parameter_ColumnDefinition">
    <xsd:choice>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Parameter_ColumnDefinition" type="Parameter_ColumnDefinition"/>
    </xsd:choice>
  </xsd:complexType>
  <xsd:complexType name="Array_Parameter_Source">
    <xsd:choice>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Parameter_Source" type="Parameter_Source"/>
    </xsd:choice>
  </xsd:complexType>
  <xsd:complexType name="Array_Parameter_WHEN">
    <xsd:choice>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Parameter_WHEN" type="Parameter_WHEN"/>
    </xsd:choice>
  </xsd:complexType>
  <xsd:complexType name="Array_Parameter_Identifier">
    <xsd:choice>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Parameter_Identifier" type="Parameter_Identifier"/>
    </xsd:choice>
  </xsd:complexType>
  <xsd:complexType name="Array_Statement">
    <xsd:choice>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="statement" type="statement"/>
    </xsd:choice>
  </xsd:complexType>
  <xsd:complexType name="Array_Parameter_ORDER_BY_item">
    <xsd:choice>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Parameter_ORDER_BY_item" type="Parameter_ORDER_BY_item"/>
    </xsd:choice>
  </xsd:complexType>
  <xsd:complexType name="Array_Parameter_Condition">
    <xsd:choice>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Parameter_Condition" type="Parameter_Condition"/>
    </xsd:choice>
  </xsd:complexType>
  <xsd:complexType name="Array_Parameter_Field">
    <xsd:choice>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Parameter_Field" type="Parameter_Field"/>
    </xsd:choice>
  </xsd:complexType>
  <xsd:complexType name="Array_expression_item">
    <xsd:choice>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Verb_SELECT" type="Verb_SELECT"/>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Parameter_Expression" type="Parameter_Expression"/>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Parameter_String" type="Parameter_String"/>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Parameter_Numeric" type="Parameter_Numeric"/>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Parameter_Identifier" type="Parameter_Identifier"/>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Parameter_Cast" type="Parameter_Cast"/>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Parameter_Function" type="Parameter_Function"/>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Parameter_IN" type="Parameter_IN"/>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Parameter_Dataset" type="Parameter_Dataset"/>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Parameter_CASE" type="Parameter_CASE"/>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Parameter_Set" type="Parameter_Set"/>
    </xsd:choice>
  </xsd:complexType>
  <xsd:complexType name="Array_tabular_expression_item">
    <xsd:choice>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Verb_SELECT" type="Verb_SELECT"/>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Parameter_Dataset" type="Parameter_Dataset"/>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="Parameter_Set" type="Parameter_Set"/>
    </xsd:choice>
  </xsd:complexType>
  <xsd:complexType name="Parameter_String">
    <xsd:all>
      <xsd:element minOccurs="0" name="string_value" type="xsd:string"/>
      <xsd:element minOccurs="0" name="escape_character" type="xsd:string"/>
      <xsd:element minOccurs="0" name="operator" type="xsd:string"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Parameter_Base">
    <xsd:all/>
  </xsd:complexType>
  <xsd:complexType name="Parameter_Condition">
    <xsd:all>
      <xsd:element minOccurs="0" name="right" type="condition_part"/>
      <xsd:element minOccurs="0" name="operator" type="xsd:string"/>
      <xsd:element minOccurs="0" name="and_or" type="and_or"/>
      <xsd:element minOccurs="0" name="left" type="condition_part"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Parameter_Expression_Item">
    <xsd:all>
      <xsd:element minOccurs="0" name="operator" type="xsd:string"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Parameter_Dataset">
    <xsd:all>
      <xsd:element minOccurs="0" name="data_source" type="data_source_types"/>
      <xsd:element minOccurs="0" name="operator" type="xsd:string"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Parameter_Expression">
    <xsd:all>
      <xsd:element minOccurs="0" name="expressionitems" type="Array_expression_item"/>
      <xsd:element minOccurs="0" name="operator" type="xsd:string"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Parameter_ORDER_BY_item">
    <xsd:all>
      <xsd:element minOccurs="0" name="direction" type="xsd:string"/>
      <xsd:element minOccurs="0" name="expressionitems" type="Array_expression_item"/>
      <xsd:element minOccurs="0" name="operator" type="xsd:string"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Parameter_Flatfile_Dataset">
    <xsd:all>
      <xsd:element minOccurs="0" name="filename" type="xsd:string"/>
      <xsd:element minOccurs="0" name="delimiter" type="xsd:string"/>
      <xsd:element minOccurs="0" name="has_header" type="xsd:boolean"/>
      <xsd:element minOccurs="0" name="csv_dialect" type="file_types"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Parameter_Cast">
    <xsd:all>
      <xsd:element minOccurs="0" name="datatype" type="datatypes"/>
      <xsd:element minOccurs="0" name="expression" type="Array_expression_item"/>
      <xsd:element minOccurs="0" name="operator" type="xsd:string"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Parameter_Numeric">
    <xsd:all>
      <xsd:element minOccurs="0" name="numeric_value" type="xsd:decimal"/>
      <xsd:element minOccurs="0" name="operator" type="xsd:string"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Parameter_WHEN">
    <xsd:all>
      <xsd:element minOccurs="0" name="result" type="Array_expression_item"/>
      <xsd:element minOccurs="0" name="conditions" type="Array_Parameter_Condition"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Parameter_ColumnDefinition">
    <xsd:all>
      <xsd:element minOccurs="0" name="default" type="xsd:string"/>
      <xsd:element minOccurs="0" name="name" type="xsd:string"/>
      <xsd:element minOccurs="0" name="notnull" type="xsd:boolean"/>
      <xsd:element minOccurs="0" name="datatype" type="datatypes"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Parameter_Set">
    <xsd:all>
      <xsd:element minOccurs="0" name="set_operator" type="set_operator"/>
      <xsd:element minOccurs="0" name="subsets" type="Array_tabular_expression_item"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Parameter_Function">
    <xsd:all>
      <xsd:element minOccurs="0" name="name" type="xsd:string"/>
      <xsd:element minOccurs="0" name="parameters" type="xsd:string"/>
      <xsd:element minOccurs="0" name="operator" type="xsd:string"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Parameter_RDBMS_Dataset">
    <xsd:all/>
  </xsd:complexType>
  <xsd:complexType name="Parameter_Identifier">
    <xsd:all>
      <xsd:element minOccurs="0" name="prefix" type="xsd:string"/>
      <xsd:element minOccurs="0" name="identifier" type="xsd:string"/>
      <xsd:element minOccurs="0" name="operator" type="xsd:string"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Parameter_Conditions">
    <xsd:all/>
  </xsd:complexType>
  <xsd:complexType name="Parameter_Source">
    <xsd:all>
      <xsd:element minOccurs="0" name="conditions" type="Array_Parameter_Condition"/>
      <xsd:element minOccurs="0" name="join_type" type="join_type"/>
      <xsd:element minOccurs="0" name="alias" type="xsd:string"/>
      <xsd:element minOccurs="0" name="expression" type="Array_expression_item"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Parameter_IN">
    <xsd:all>
      <xsd:element minOccurs="0" name="in_values" type="in_types"/>
      <xsd:element minOccurs="0" name="operator" type="xsd:string"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Parameter_Constraint">
    <xsd:all>
      <xsd:element minOccurs="0" name="checkconditions" type="Array_Parameter_Condition"/>
      <xsd:element minOccurs="0" name="references" type="Array_Parameter_Identifier"/>
      <xsd:element minOccurs="0" name="name" type="xsd:string"/>
      <xsd:element minOccurs="0" name="constraint_type" type="constraint_types"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Parameter_DML">
    <xsd:all/>
  </xsd:complexType>
  <xsd:complexType name="Parameter_XML_Dataset">
    <xsd:all/>
  </xsd:complexType>
  <xsd:complexType name="Parameter_Matrix_Dataset">
    <xsd:all/>
  </xsd:complexType>
  <xsd:complexType name="Parameter_CASE">
    <xsd:all>
      <xsd:element minOccurs="0" name="when_statements" type="Array_Parameter_WHEN"/>
      <xsd:element minOccurs="0" name="else_statement" type="Array_expression_item"/>
      <xsd:element minOccurs="0" name="operator" type="xsd:string"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Parameter_Field">
    <xsd:all>
      <xsd:element minOccurs="0" name="alias" type="xsd:string"/>
      <xsd:element minOccurs="0" name="expression" type="Array_expression_item"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Verb_INSERT">
    <xsd:all>
      <xsd:element minOccurs="0" name="destination_identifier" type="Parameter_Identifier"/>
      <xsd:element minOccurs="0" name="column_identifiers" type="Array_Parameter_Identifier"/>
      <xsd:element minOccurs="0" name="data" type="tabular_expression_item"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Verb_CREATE_TABLE">
    <xsd:all>
      <xsd:element minOccurs="0" name="name" type="xsd:string"/>
      <xsd:element minOccurs="0" name="constraints" type="Array_Parameter_Constraint"/>
      <xsd:element minOccurs="0" name="columns" type="Array_Parameter_ColumnDefinition"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Verb_CREATE_INDEX">
    <xsd:all>
      <xsd:element minOccurs="0" name="index_type" type="index_types"/>
      <xsd:element minOccurs="0" name="name" type="xsd:string"/>
      <xsd:element minOccurs="0" name="columnnames" type="Array_string"/>
      <xsd:element minOccurs="0" name="tablename" type="xsd:string"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Verb_SELECT">
    <xsd:all>
      <xsd:element minOccurs="0" name="order_by" type="Array_Parameter_ORDER_BY_item"/>
      <xsd:element minOccurs="0" name="fields" type="Array_Parameter_Field"/>
      <xsd:element minOccurs="0" name="sources" type="Array_Parameter_Source"/>
      <xsd:element minOccurs="0" name="top_limit" type="xsd:integer"/>
      <xsd:element minOccurs="0" name="operator" type="xsd:string"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Verb_DELETE">
    <xsd:all>
      <xsd:element minOccurs="0" name="sources" type="Array_Parameter_Source"/>
      <xsd:element minOccurs="0" name="operator" type="xsd:string"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="Verb_Custom">
    <xsd:all>
      <xsd:element minOccurs="0" name="sql_oracle" type="xsd:string"/>
      <xsd:element minOccurs="0" name="sql_sqlserver" type="xsd:string"/>
      <xsd:element minOccurs="0" name="sql_db2" type="xsd:string"/>
      <xsd:element minOccurs="0" name="sql_postgresql" type="xsd:string"/>
      <xsd:element minOccurs="0" name="sql_mysql" type="xsd:string"/>
    </xsd:all>
  </xsd:complexType>
  <xsd:element name="statement" type="statement"/>
</xsd:schema>

=== Omkaragrawal/qal/qal/sql/tests/resources/_test_CREATE_TABLE_in.xml
<?xml version="1.0" ?><sql:statement xmlns:sql="http://www.optimalbpm.se/XMLschema/DAL/SQL" xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="http://www.optimalbpm.se/XMLschema/DAL/SQL ../../SQL.xsd"><sql:Verb_CREATE_TABLE><sql:columns><sql:Parameter_ColumnDefinition><sql:datatype>serial</sql:datatype><sql:default/><sql:name>Table1ID</sql:name><sql:notnull>True</sql:notnull></sql:Parameter_ColumnDefinition><sql:Parameter_ColumnDefinition><sql:datatype>varchar(400)</sql:datatype><sql:default/><sql:name>Table1Name</sql:name><sql:notnull>False</sql:notnull></sql:Parameter_ColumnDefinition><sql:Parameter_ColumnDefinition><sql:datatype>timestamp</sql:datatype><sql:default>::currdatetime::</sql:default><sql:name>Table1Changed</sql:name><sql:notnull>False</sql:notnull></sql:Parameter_ColumnDefinition></sql:columns><sql:constraints><sql:Parameter_Constraint><sql:checkconditions/><sql:constraint_type>PRIMARY KEY</sql:constraint_type><sql:name>PK_Table1_Table1ID</sql:name><sql:references><sql:Parameter_Identifier><sql:identifier>Table1ID</sql:identifier><sql:operator>C</sql:operator><sql:prefix/></sql:Parameter_Identifier></sql:references></sql:Parameter_Constraint><sql:Parameter_Constraint><sql:checkconditions/><sql:constraint_type>FOREIGN KEY</sql:constraint_type><sql:name>FK_Table1_Table1ID_Table2_Table2ID</sql:name><sql:references><sql:Parameter_Identifier><sql:identifier>Table1ID</sql:identifier><sql:operator>C</sql:operator><sql:prefix/></sql:Parameter_Identifier><sql:Parameter_Identifier><sql:identifier>Table2</sql:identifier><sql:operator>C</sql:operator><sql:prefix/></sql:Parameter_Identifier><sql:Parameter_Identifier><sql:identifier>Table2ID</sql:identifier><sql:operator>C</sql:operator><sql:prefix/></sql:Parameter_Identifier></sql:references></sql:Parameter_Constraint><sql:Parameter_Constraint><sql:checkconditions><sql:Parameter_Condition><sql:and_or>AND</sql:and_or><sql:left><sql:Parameter_Numeric><sql:numeric_value>1.3</sql:numeric_value><sql:operator>+</sql:operator></sql:Parameter_Numeric></sql:left><sql:operator>&gt;</sql:operator><sql:right><sql:Parameter_Numeric><sql:numeric_value>2.4</sql:numeric_value><sql:operator>+</sql:operator></sql:Parameter_Numeric></sql:right></sql:Parameter_Condition><sql:Parameter_Condition><sql:and_or>AND</sql:and_or><sql:left><sql:Parameter_Identifier><sql:identifier>firstname</sql:identifier><sql:operator>C</sql:operator><sql:prefix>T1</sql:prefix></sql:Parameter_Identifier></sql:left><sql:operator>LIKE</sql:operator><sql:right><sql:Parameter_String><sql:escape_character/><sql:operator>+</sql:operator><sql:string_value>%icklas</sql:string_value></sql:Parameter_String></sql:right></sql:Parameter_Condition></sql:checkconditions><sql:constraint_type>CHECK</sql:constraint_type><sql:name>CK_Table1_Name</sql:name><sql:references><sql:Parameter_Identifier><sql:identifier>Table1ID</sql:identifier><sql:operator>C</sql:operator><sql:prefix/></sql:Parameter_Identifier></sql:references></sql:Parameter_Constraint><sql:Parameter_Constraint><sql:checkconditions/><sql:constraint_type>UNIQUE</sql:constraint_type><sql:name>UQ_Table1_Name</sql:name><sql:references><sql:Parameter_Identifier><sql:identifier>Table1ID</sql:identifier><sql:operator>C</sql:operator><sql:prefix/></sql:Parameter_Identifier></sql:references></sql:Parameter_Constraint></sql:constraints><sql:name>Table1</sql:name></sql:Verb_CREATE_TABLE></sql:statement>

=== Omkaragrawal/qal/qal/sql/tests/resources/_test_UPDATE_in.xml
<?xml version="1.0" ?><sql:statement xmlns:sql="http://www.optimalbpm.se/XMLschema/DAL/SQL" xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="http://www.optimalbpm.se/XMLschema/DAL/SQL ../../SQL.xsd"><sql:Verb_UPDATE><sql:assignments><sql:Parameter_Assignment><sql:left><sql:Parameter_Identifier><sql:identifier>dest_column</sql:identifier><sql:operator>C</sql:operator><sql:prefix/></sql:Parameter_Identifier></sql:left><sql:right><sql:Parameter_String><sql:escape_character/><sql:operator>C</sql:operator><sql:string_value>Hello</sql:string_value></sql:Parameter_String></sql:right></sql:Parameter_Assignment></sql:assignments><sql:conditions><sql:Parameter_Condition><sql:and_or>AND</sql:and_or><sql:left><sql:Parameter_Identifier><sql:identifier>col_1</sql:identifier><sql:operator>C</sql:operator><sql:prefix/></sql:Parameter_Identifier></sql:left><sql:operator>=</sql:operator><sql:right><sql:Parameter_String><sql:escape_character/><sql:operator>C</sql:operator><sql:string_value>1</sql:string_value></sql:Parameter_String></sql:right></sql:Parameter_Condition><sql:Parameter_Condition><sql:and_or>AND</sql:and_or><sql:left><sql:Parameter_Identifier><sql:identifier>col_2</sql:identifier><sql:operator>C</sql:operator><sql:prefix/></sql:Parameter_Identifier></sql:left><sql:operator>=</sql:operator><sql:right><sql:Parameter_String><sql:escape_character/><sql:operator>C</sql:operator><sql:string_value>1</sql:string_value></sql:Parameter_String></sql:right></sql:Parameter_Condition></sql:conditions><sql:table_identifier><sql:Parameter_Identifier><sql:identifier/><sql:operator>C</sql:operator><sql:prefix/></sql:Parameter_Identifier></sql:table_identifier></sql:Verb_UPDATE></sql:statement>

=== Omkaragrawal/qal/qal/sql/tests/resources/_test_SELECT_resource_in.xml
<sql:statement xmlns:sql="http://www.unifiedbpm.se/XMLschema/DAL/SQL" xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="http://www.unifiedbpm.se/XMLschema/DAL/SQL ../../dal/SQL.xsd">

	<sql:Verb_SELECT>
		<sql:order_by/>
		<sql:fields>
			<sql:Parameter_Field>
				<sql:alias></sql:alias>
				<sql:expression>
					<sql:Parameter_Identifier>
						<sql:identifier>table_postgresID</sql:identifier>
						<sql:prefix>PG</sql:prefix>
						<sql:operator></sql:operator>
					</sql:Parameter_Identifier>
				</sql:expression>
			</sql:Parameter_Field>
			<sql:Parameter_Field>
				<sql:alias></sql:alias>
				<sql:expression>
					<sql:Parameter_Identifier>
						<sql:identifier>table_mysqlID</sql:identifier>
						<sql:prefix>MY</sql:prefix>
						<sql:operator></sql:operator>
					</sql:Parameter_Identifier>
				</sql:expression>
			</sql:Parameter_Field>
			<sql:Parameter_Field>
				<sql:alias></sql:alias>
				<sql:expression>
					<sql:Parameter_Identifier>
						<sql:identifier>table_postgresName</sql:identifier>
						<sql:prefix>PG</sql:prefix>
						<sql:operator></sql:operator>
					</sql:Parameter_Identifier>
				</sql:expression>
			</sql:Parameter_Field>
			<sql:Parameter_Field>
				<sql:alias></sql:alias>
				<sql:expression>
					<sql:Parameter_Identifier>
						<sql:identifier>table_mysqlName</sql:identifier>
						<sql:prefix>MY</sql:prefix>
						<sql:operator></sql:operator>
					</sql:Parameter_Identifier>
				</sql:expression>
			</sql:Parameter_Field>
			<sql:Parameter_Field>
				<sql:alias></sql:alias>
				<sql:expression>
					<sql:Parameter_Identifier>
						<sql:identifier>file_csvName</sql:identifier>
						<sql:prefix>CSV</sql:prefix>
						<sql:operator></sql:operator>
					</sql:Parameter_Identifier>
				</sql:expression>
			</sql:Parameter_Field>
		</sql:fields>
		<sql:sources>
			<sql:Parameter_Source>
				<sql:conditions/>
				<sql:join_type>INNER</sql:join_type>
				<sql:alias>PG</sql:alias>
				<sql:expression>
					<sql:Parameter_Identifier>
						<sql:identifier>table_postgres</sql:identifier>
						<sql:prefix></sql:prefix>
						<sql:operator></sql:operator>
					</sql:Parameter_Identifier>
				</sql:expression>
				<sql:resource_uuid>{1D62083E-88F7-4442-920D-0B6CC59BA2FF}</sql:resource_uuid>
			</sql:Parameter_Source>
			<sql:Parameter_Source>
				<sql:conditions>
					<sql:Parameter_Condition>
						<sql:right>
							<sql:Parameter_Identifier>
								<sql:identifier>table_mysqlID</sql:identifier>
								<sql:prefix>MY</sql:prefix>
								<sql:operator></sql:operator>
							</sql:Parameter_Identifier>
						</sql:right>
						<sql:and_or>AND</sql:and_or>
						<sql:operator>=</sql:operator>
						<sql:left>
							<sql:Parameter_Identifier>
								<sql:identifier>table_postgresID</sql:identifier>
								<sql:prefix>PG</sql:prefix>
								<sql:operator></sql:operator>
							</sql:Parameter_Identifier>
						</sql:left>
					</sql:Parameter_Condition>
				</sql:conditions>
				<sql:join_type>INNER</sql:join_type>
				<sql:alias>MY</sql:alias>
				<sql:expression>
					<sql:Parameter_Identifier>
						<sql:identifier>table_mysql</sql:identifier>
						<sql:prefix></sql:prefix>
						<sql:operator></sql:operator>
					</sql:Parameter_Identifier>
				</sql:expression>
				<sql:resource_uuid>{DD34A233-47A6-4C16-A26F-195711B49B97}</sql:resource_uuid>
			</sql:Parameter_Source>
			<sql:Parameter_Source>
				<sql:conditions>
					<sql:Parameter_Condition>
						<sql:right>
							<sql:Parameter_Cast>
								<sql:datatype>integer</sql:datatype>
								<sql:expression>
									<sql:Parameter_Identifier>
										<sql:identifier>file_csvID</sql:identifier>
										<sql:prefix>CSV</sql:prefix>
										<sql:operator></sql:operator>
									</sql:Parameter_Identifier>
								</sql:expression>
								<sql:operator></sql:operator>
							</sql:Parameter_Cast>
						</sql:right>
						<sql:and_or>AND</sql:and_or>
						<sql:operator>=</sql:operator>
						<sql:left>
							<sql:Parameter_Identifier>
								<sql:identifier>table_postgresID</sql:identifier>
								<sql:prefix>PG</sql:prefix>
								<sql:operator></sql:operator>
							</sql:Parameter_Identifier>
						</sql:left>
					</sql:Parameter_Condition>
				</sql:conditions>
				<sql:join_type>INNER</sql:join_type>
				<sql:alias>CSV</sql:alias>
				<sql:expression>
					<sql:Parameter_NoSQL>
						<sql:data_source>Flatfile_Dataset</sql:data_source>
						<sql:operator></sql:operator>
						<sql:resource_uuid>{86470370-FF78-48A4-9759-A3BAE4EE22FE}</sql:resource_uuid>
					</sql:Parameter_NoSQL>
				</sql:expression>
			</sql:Parameter_Source>
		</sql:sources>
		<sql:top_limit>1</sql:top_limit>
		<sql:operator></sql:operator>
		<sql:resource_uuid>{1D62083E-88F7-4442-920D-0B6CC59BA2FF}</sql:resource_uuid>
	</sql:Verb_SELECT>
	<resources>
	
		<resource type="rdbms" uuid="{1D62083E-88F7-4442-920D-0B6CC59BA2FF}" caption="localhost_pg">
			<server>localhost</server>
			<db_type>PostgreSQL</db_type>
			<database>ubpmtest</database>		
			<username>ubpmuser</username>
			<password>test</password>
		</resource>
		<resource type="rdbms" uuid="{DD34A233-47A6-4C16-A26F-195711B49B97}" caption="localhost_mysql">
			<server>localhost</server>
			<db_type>MySQL</db_type>
			<database>ubpmtest</database>		
			<username>ubpmuser</username>
			<password>test</password>
		</resource>
		<resource type="flatfile" uuid="{86470370-FF78-48A4-9759-A3BAE4EE22FE}" caption="csv-file">
			<filename>resources/_test_SELECT_resource_csv_in.txt</filename>
			<delimiter>,</delimiter>
			<has_header>True</has_header>
			<csv_dialect>csv</csv_dialect>
		</resource>		
		
	</resources>

</sql:statement>
